### ISSUE TITLE
patch of nan data produces mostly empty plot?

### ISSUE THREAD

**Issue by water-e** [alsauve/scaleogram#11]
Hi I have some data sampled at a period of 0.25 hours, so t[0] = 0.0 and t[1]=0.25. There are patches of missing data. I was trying to plot the amplitude as follows:
```
scales = np.arange(2,512,2)
ax = scg.cws(t, sig, scales, figsize=(12,6), ylabel="Period [Hours]", 
             xlabel='Hour', yscale='log',coikw={'alpha':0.5,'hatch':'/'},wavelet='cmor3-0.96') 
```
The problem is that for "full-strength" stretches of the data the plot is mostly empty except for some values at very small periods. If I prune to a smaller series with little/no empty data, everything is fine. It doesn't seem to be a property of the pywavelets cmor3-0.96 transform itself. When I plot the cwt coef matrix myself using contourf using cookbook recipes from the web I do get sensible values, but of course the formatting isn't anywhere near as beautiful as it is when produced by your module. Is this expected? Does it have to do with implementation details of the convolution? I can supply the data and full example if this doesn't have a simple explanation.

**Comment by alsauve** [comment]
Hi @water-e .

The NaN issue is unfortunately problematic for algorithms such as Fourier or Wavelet transform as the integration
of values containing NaNs, which are absorbant, outputs a NaN as the final result. This behaviour is in fact very useful and desirable but it is another topic.

To put it simply, the missing values are to be provided by you in order to produce a valid result.
Hence you have two options
1. set NaNs to zero in order to produce a plot, in this case I would recommend to remove the average value of the remaining signal for better results
2. replace missing value by an appropriate interpolation 

Unfortunately, missing data is never recoverable and both solutions results in some kind of blurring  (wings) in the frequency domain of the result.
